/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package asetku.frames;

import asetku.databases.ConnectionManager;
import asetku.databases.UserSession;
import asetku.utils.Utilities;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author dhafa
 */
public class MainFrame extends javax.swing.JFrame {
    Connection conn = ConnectionManager.getInstance().getConnection();
    /** Creates new form MainFrame */
    public MainFrame() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        setLocation(dim.width / 2 - getSize().width / 2, dim.height / 2 - getSize().height / 2);
        initData();
        
        if(UserSession.getCurrentUser().getRoleId().equals("1")) {
            jTabbedPane1.remove(budgetPanel1);
        }
    }
    
    private void initData() {
        System.err.println();
        String query = "SELECT users.*, divisi.budget, cabang.nama as nama_cabang, roles.nama as nama_role\n" +
                        "FROM users\n" +
                        "JOIN roles ON roles.id=users.role_id\n" +
                        "JOIN divisi ON divisi.id=users.divisi_id\n" + 
                        "JOIN cabang ON cabang.id=divisi.cabang_id\n" +
                        "WHERE users.id=?";
        try {
            PreparedStatement stmt = conn.prepareStatement(query);
            stmt.setString(1, UserSession.getCurrentUser().getId());
            
            ResultSet result = stmt.executeQuery();
            
            if(result.next()) {
                nipLabel.setText(result.getString("users.nip"));
                cabangLabel.setText(result.getString("nama_cabang"));
                roleLabel.setText(result.getString("nama_role"));
                namaLabel.setText(result.getString("users.nama"));
                budgetDivisi.setText(Utilities.getFormatCurrency().format(result.getDouble("divisi.budget")));
            }
        } catch (SQLException e) {
            System.err.println(e.getMessage());
        }
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        namaLabel = new javax.swing.JLabel();
        cabangLabel = new javax.swing.JLabel();
        nipLabel = new javax.swing.JLabel();
        roleLabel = new javax.swing.JLabel();
        budgetDivisi = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        asetPanel1 = new asetku.panels.AsetPanel();
        allAsetPanel1 = new asetku.panels.AllAsetPanel();
        pembelianPanel1 = new asetku.panels.PembelianPanel();
        budgetPanel1 = new asetku.panels.BudgetPanel();
        historyPanel1 = new asetku.panels.HistoryPanel();
        vendorPanel1 = new asetku.panels.VendorPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 255, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        namaLabel.setText("Nama :");
        jPanel2.add(namaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 160, -1));

        cabangLabel.setText("Cabang :");
        jPanel2.add(cabangLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 160, -1));

        nipLabel.setText("NIP : ");
        jPanel2.add(nipLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 160, -1));

        roleLabel.setText("jLabel1");
        jPanel2.add(roleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 160, -1));

        budgetDivisi.setText("jLabel1");
        jPanel2.add(budgetDivisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 160, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 530));

        jTabbedPane1.addTab("Data Aset", asetPanel1);
        jTabbedPane1.addTab("Data Aset Seluruh Cabang", allAsetPanel1);
        jTabbedPane1.addTab("Data Pembelian", pembelianPanel1);
        jTabbedPane1.addTab("Mutasi Budget", budgetPanel1);
        jTabbedPane1.addTab("History Mutasi", historyPanel1);
        jTabbedPane1.addTab("Data Vendor", vendorPanel1);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 810, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private asetku.panels.AllAsetPanel allAsetPanel1;
    private asetku.panels.AsetPanel asetPanel1;
    private javax.swing.JLabel budgetDivisi;
    private asetku.panels.BudgetPanel budgetPanel1;
    private javax.swing.JLabel cabangLabel;
    private asetku.panels.HistoryPanel historyPanel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel namaLabel;
    private javax.swing.JLabel nipLabel;
    private asetku.panels.PembelianPanel pembelianPanel1;
    private javax.swing.JLabel roleLabel;
    private asetku.panels.VendorPanel vendorPanel1;
    // End of variables declaration//GEN-END:variables

}
